# /etc/nginx/sites-available/pelhamblueband.conf

# be sure to add symlink to /etc/nginx/sites-enabled

# Redirect all HTTP to HTTPS
server {
    listen 80;
    server_name pelhamblueband.com www.pelhamblueband.com;
    return 301 https://$host$request_uri;
}

# Main app
server {
    listen 443 ssl http2;
    server_name pelhamblueband.com www.pelhamblueband.com;

    include snippets/ssl-pelhamblueband.conf;
    include snippets/security-headers.conf;

    access_log /var/www/pelhamblueband.com/logs/nginx-access.log;
    error_log  /var/www/pelhamblueband.com/logs/nginx-error.log;

    location / {
        include snippets/proxy-params.conf;
        proxy_pass http://127.0.0.1:4044;
    }
}

